name: 'Setup Node.js'
description: 'Setup Node.js environment'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
  cache:
    description: 'Cache type'
    required: false
  registry-url:
    description: 'NPM registry URL'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        registry-url: ${{ inputs.registry-url }} 